import flet as ft
from features.prompting.ui.screens.prompt_creation.prompt_creation_view_model import PromptCreationViewModel

@ft.component
def PromptEditor(vm: PromptCreationViewModel) -> ft.Container:
    """
    Main editor component for creating prompts.

    Purpose: Provides text areas for source context and generated output, plus action buttons.
    Usage: Injected with PromptCreationViewModel to access project state.
    Key UI Elements: Info bar, main editing area (EditorMainArea), footer.
    Used In: PromptCreationView.
    """
    state, _ = ft.use_state(vm.state)

    return ft.Container(
        expand=True,
        padding=ft.Padding(left=10, top=0, right=10, bottom=0),
        content=ft.Column(
            controls=[
                EditorInfoBar(state.project_name, state.project_path),
                EditorMainArea(),
                EditorFooter(),
            ],
            spacing=10,
            expand=True,
        )
    )

@ft.component
def EditorMainArea() -> ft.Column:
    """
    Main layout for the editor's interactive area.

    Purpose: Organizes the prompt edition area, action buttons, and translated result area.
    Key UI Elements: Prompt edition section, action center, translated prompt section.
    Used In: PromptEditor.
    """
    return ft.Column(
        controls=[
            PromptEditionSection(),
            EditorActionCenter(),
            TranslatedPromptSection(),
        ],
        spacing=5,
        expand=True,
    )

@ft.component
def PromptEditionSection() -> ft.Column:
    """
    Component for inputting source context or prompt data.

    Purpose: Provides a large text area for users to edit the source prompt or whisper output.
    Key UI Elements: Labeled text field with outline border.
    Used In: EditorMainArea.
    """
    return ft.Column(
        controls=[
            ft.TextField(
                label="Source Context / Whisper Output",
                multiline=True,
                expand=False,
                min_lines=8,
                border=ft.InputBorder.OUTLINE,
                border_color=ft.Colors.OUTLINE_VARIANT,
                focused_border_color=ft.Colors.PRIMARY,
                text_size=14,
                dense=True,
            ),
        ],
        alignment=ft.MainAxisAlignment.CENTER,
        horizontal_alignment=ft.CrossAxisAlignment.STRETCH,
        expand=2,
    )

@ft.component
def TranslatedPromptSection() -> ft.Column:
    """
    Component for displaying and editing the translated or generated prompt.

    Purpose: Provides a text area for the output generated by the translation/prompting logic.
    Key UI Elements: Labeled text field with outline border.
    Used In: EditorMainArea.
    """
    return ft.Column(
        controls=[
            ft.TextField(
                label="Generated Prompt / Translation",
                multiline=True,
                expand=False,
                min_lines=8,
                border=ft.InputBorder.OUTLINE,
                border_color=ft.Colors.OUTLINE_VARIANT,
                focused_border_color=ft.Colors.SECONDARY,
                text_size=14,
                dense=True,
            )
        ],
        horizontal_alignment=ft.CrossAxisAlignment.STRETCH,
        alignment=ft.MainAxisAlignment.CENTER,
        expand=2,
    )


@ft.component
def EditorInfoBar(project_name: str, project_path: str) -> ft.Container:
    """
    Displays the current project's name and path.

    Purpose: Provide context about the active project within the editor.
    Key UI Elements: Info icon, project metadata, status indicator.
    Used In: PromptEditor.
    """
    return ft.Container(
        padding=10,
        bgcolor=ft.Colors.SURFACE_CONTAINER_HIGHEST,
        border_radius=8,
        content=ft.Row([
            ft.Icon(ft.Icons.INFO_OUTLINE, size=20, color=ft.Colors.PRIMARY),
            ft.Text(
                f"Project: {project_name} | {project_path}", 
                size=13, 
                weight=ft.FontWeight.W_500, 
                color=ft.Colors.ON_SURFACE_VARIANT
            ),
            ft.VerticalDivider(),
            ft.Text("Status: Ready", size=13, color=ft.Colors.SECONDARY)
        ])
    )

@ft.component
def EditorActionCenter() -> ft.Container:
    """
    Center action controls for prompt generation.

    Purpose: Contains the primary trigger for translating or generating content.
    Key UI Elements: Custom action button with text and icons.
    Used In: PromptEditor.
    """
    return ft.Container(
        expand=1,
        content=ft.Row(
            alignment=ft.MainAxisAlignment.CENTER,
            controls=[
                ft.Container(
                    content=ft.Row(
                        controls=[
                            ft.Icon(ft.Icons.KEYBOARD_ARROW_DOWN_ROUNDED, color=ft.Colors.ON_PRIMARY),
                            ft.Text("translate", color=ft.Colors.ON_PRIMARY, weight=ft.FontWeight.BOLD),
                            ft.Icon(ft.Icons.KEYBOARD_ARROW_DOWN_ROUNDED, color=ft.Colors.ON_PRIMARY),
                        ],
                        tight=True,
                        spacing=10,
                    ),
                    padding=ft.Padding(left=25, top=12, right=25, bottom=12),
                    border_radius=30,
                    bgcolor=ft.Colors.PRIMARY,
                    on_click=lambda _: print("Translate action"),
                    shadow=ft.BoxShadow(
                        blur_radius=10, 
                        color=ft.Colors.with_opacity(0.3, ft.Colors.BLACK)
                    )
                )
            ]
        ),
    )

@ft.component
def EditorFooter() -> ft.Row:
    """
    Bottom action bar for secondary editor operations.

    Purpose: Provides copy and other utility actions.
    Key UI Elements: Copy to clipboard button centered.
    Used In: PromptEditor.
    """
    return ft.Row(
        alignment=ft.MainAxisAlignment.CENTER,
        controls=[
            ft.Button(
                "Copy to Clipboard",
                icon=ft.Icons.CONTENT_COPY_ROUNDED,
                style=ft.ButtonStyle(
                    color=ft.Colors.ON_SECONDARY_CONTAINER,
                    bgcolor=ft.Colors.SECONDARY_CONTAINER,
                    padding=20,
                ),
                on_click=lambda _: print("Copy to clipboard")
            )
        ]
    )
